{{- if .Values.ragInit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openprodoc.fullname" . }}-rag-init
  labels:
    {{- include "openprodoc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  openwebui-password: {{ .Values.ragInit.config.watcherPassword | quote }}
{{- end }}
