{{- $secret := lookup "v1" "Secret" .Release.Namespace "openprodoc-secrets" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: openprodoc-secrets
  labels:
    {{- include "openprodoc.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  db-user: {{ .Values.coreEngine.config.database.user | required "coreEngine.config.database.user is required" | quote }}
  db-password: {{ .Values.coreEngine.config.database.password | required "coreEngine.config.database.password is required" | quote }}

  # Core Engine credentials
  root-password: {{ .Values.coreEngine.config.install.rootPassword | required "coreEngine.config.install.rootPassword is required" | quote }}
  main-key: {{ .Values.coreEngine.config.install.mainKey | required "coreEngine.config.install.mainKey is required" | quote }}
 {{- end }}  
